---
 - name: Create etcd directories 
   file:
     path: "/etc/etcd"
     state: directory
   become: yes

 - name: Copy Certs and Config to Controllers
   copy:
     src: '{{ item.source }}'
     dest: '{{ item.dest }}'
     mode: '{{ item.mode }}'
   with_items:
   - { source: "{{ ca_pem_file }}",   dest: "{{ etcd_config_dir }}/ca.pem",               mode: "0664" }
   - { source: "{{ k8s_pem_file }}",  dest: "{{ etcd_config_dir }}/kubernetes.pem",       mode: "0664" }
   - { source: "{{ k8s_key_file }}",  dest: "{{ etcd_config_dir }}/kubernetes-key.pem",   mode: "0600" }
   become: yes

 - name: Unpack the etcd binaries on each controller
   unarchive:
     remote_src: yes
     src: "{{ etcd_url }}"
     dest: /tmp
   become: yes

 - name: Move etcd binaries to /usr/local/bin path
   copy:
     src: '{{ item.source }}' 
     dest: '{{ item.dest }}' 
     remote_src: yes
     mode: "0775"
   with_items:
   - { source: "{{ etcd_extracted_dir }}/etcd", dest: /usr/local/bin/etcd }
   - { source: "{{ etcd_extracted_dir }}/etcdctl", dest: /usr/local/bin/etcdctl }
   become: yes

 - name: Push etcd service config
   template: 
     src: "{{ role_path }}/templates/etcd.service.j2"
     dest: /etc/systemd/system/etcd.service 
   vars:
     cluster_size: "{{ groups['controllers'] | length | int }}"
   become: yes    

 - name: Reload systemd manager
   command: systemctl daemon-reload
   become: yes
   
 - name: Reload the daemon for the services
   systemd: 
     name: etcd.service 
     enabled: yes
     state: restarted
   become: yes
