---
- name: Kubernetes Conformance Testing
  hosts: localhost
  connection: local
  vars:
    sonobuoy_tar: "sonobuoy_0.18.0_linux_amd64.tar.gz"
    sonobuoy_version_link: "https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.18.0/sonobuoy_0.18.0_linux_amd64.tar.gz"

  tasks:
  - name: Warning!
    debug: msg="Make sure you have installed kubernetes-the-alta3-way before running this playbook!"

  - name: Apt install GoLang
    apt:
      name: golang
    become: yes

  - name: Download and Untar Conformance Testing Software
    unarchive:
      src: "{{ sonobuoy_version_link }}"
      dest: "~/"
      remote_src: yes

  - name: Run the full conformance test
    command: "/home/student/sonobuoy run --mode=certified-conformance"
