---
all:
  vars:
    ansible_user:               student
    ansible_python_interpreter: /usr/bin/python3
  children:  
    controllers:
      hosts:
        controller:
          ansible_host: controller
      vars: 
        public_ip: "{{ ansible_default_ipv4.address }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    etcd:
        children:
            controllers
    nodes:
      hosts:
        node-1:
          ansible_host: node-1
        node-2:
          ansible_host: node-2
      vars: 
        public_ip: "{{ ansible_default_ipv4.address }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    bchds:
      hosts:
        bchd:
          ansible_host: bchd
      vars:
        public_ip: "{{ ansible_default_ipv4.address }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
