apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      type tail
      format none
      path /var/log/1.log
      pos_file /var/log/1.log.pos
      tag count.format1
    </source>

    <source>
      type tail
      format none
      path /var/log/2.log
      pos_file /var/log/2.log.pos
      tag count.format2
    </source>

    <match **>
      @type http

      endpoint http://{{BCHD_IP}}:10001/logs
      open_timeout 2

      <format>
        @type json
      </format>
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
