apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox
spec:
  selector:
    matchLabels:
      app: nfs-busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-busybox
    spec:
      containers:
      - image: busybox:1.35.0
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: nfs-vol
            mountPath: "/mnt"
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-claim
