apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
  labels:
    purpose: demonstrate-configmaps
spec:
  containers:
    - name: configmap-demo-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom:
        - configMapRef:
            name: my-configmap
