apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
data:
  # username=${echo "user2" | base64)
  # password=${echo "password2" | base64)
  username: dXNlcjIK
  password: cGFzc3dvcmQyCg==
