apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  selector:
    matchLabels:
      app: nfs-web
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
      - name: web
        image: nginx:1.19.6
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: nfs-vol
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-claim
