apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: walnuts
  name: walnuts-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
