
- name: Generate cluster dns installation yaml file
  template:
    src: "{{ role_path }}/templates/kube-dns.yaml.j2" 
    dest: "{{ config_dir }}/kube-dns.yaml"

- name: Apply cluser dns service 
  command: kubectl apply -f {{ config_dir }}/kube-dns.yaml 
