- name: Copy rbac cluster-role to controllers
  copy:
    src: "{{ controller_rbac_role.file }}"
    dest: "{{ controller_rbac_role.path }}"

- name: Apply the RBAC rules
  shell: "kubectl apply -f {{ controller_rbac_role.path }}"

- name: Copy the cluster role bind file to the controllers
  copy:
    src: "{{ controller_rbac_rolebind.file }}"
    dest: "{{ controller_rbac_rolebind.path }}"

- name: Bind the clusterrole to the kubernetes user.
  shell: "kubectl apply -f {{ controller_rbac_rolebind.path }}"
