apiVersion: v1
kind: Service
metadata:
  name: bluegreen
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: bluegreen
    version: v1.0
  sessionAffinity: None
  type: ClusterIP
