apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linus-cluster-pod-watcher
subjects:
- kind: User
  name: linus
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: ClusterRole
 name: cluster-pod-watcher
 apiGroup: rbac.authorization.k8s.io
