apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: CA_DATA
    server: SERVER
  name: CLUSTER_NAME
contexts:
- context:
    cluster: CLUSTER_NAME
    user: charlie
  name: CLUSTER_NAME
current-context: CLUSTER_NAME
users:
- name: charlie
  user:
    token: USER_TOKEN
