apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: CA_DATA
    server: SERVER
  name: CLUSTER_NAME
contexts:
- context:
    cluster: CLUSTER_NAME
    user: linus
  name: CLUSTER_NAME
current-context: CLUSTER_NAME
users:
- name: linus
  user:
    token: USER_TOKEN
