---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configured
  labels:
    app: nginx-configured
spec:
  containers:
  - name: nginx
    image: nginx:1.18.0
    ports:
    - containerPort: 80
    volumeMounts:                           # these 3 files are to be injected into the container
    - name: nginx-base-config              ## links to spec.volumes.name[0] below
      mountPath: /etc/nginx/nginx.conf      # the path inside the container
      subPath: nginx.conf                   # mandatory if file exists in the container
    - name: zork                           ## links to spec.volumes.name[1] below
      mountPath: /var/www/index.html        # the path inside the container
      subPath: index.html                   # mandatory if file exists in the container
    - name: georgeorwell                   ## links to spec.volumes.name[2] below
      mountPath: /var/www/static/1984.txt   # the path inside the container
      subPath: 1984.txt                     # mandatory if file exists in the container
  volumes:
  - name: nginx-base-config                ## links to spec.containers[0]volumeMounts[0]name above
    configMap:
      name: nginx-base-conf                 # The nginx-conf.yaml configmap
  - name: zork                             ## links to spec.containers[0]volumeMounts[1]name above
    configMap:
      name: index-html-zork                 # The index.html.yaml configmap
  - name: georgeorwell                     ## links to spec.containers[0]volumeMounts[2]name above
    configMap:
      name: nineteen-eighty-four            # The nineteen-eighty-four.yaml configmap
