apiVersion: v1
kind: Pod
metadata:
   name: podsecret2
spec:
  containers:
    - name: opensusepod
      image: opensuse/leap
      command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: password
