apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-user
  namespace: default
roleRef:
  kind: Role
  name: pointy-haired-boss
  apiGroup: rbac.authorization.k8s.io

