apiVersion: v1
kind: Pod
metadata:
  name: too-little-cpu-pod
spec:
  containers:
  - name: too-little-cpu-pod
    image: nginx:1.19.6
    resources:
      limits:
        cpu: "100m"
        memory: 100Mi
