---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-pack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: redis
        name: patch-demo-ctr-2
      - image: nginx:1.19.6
        name: patch-demo-ctr
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: test-team
