---
 - name: Install nginx for localhost loadbalancing access to the HA controllers
   apt:
    name: nginx
    state: present
   become: yes
 
 - name: Create the config file for nginx
   template:
     src: "{{ role_path }}/templates/nginx.conf.j2"
     dest: "/etc/nginx/nginx.conf"
   become: yes
 
 - name: Start the nginx service
   systemd:
     name: nginx
     daemon_reload: yes
     state: restarted
     enabled: yes
   become: yes
