apiVersion: v1
kind: Pod
metadata:
  name: ringo
  labels:
    band: beatles
    role: drums
spec:
  containers:
  - name: band
    image: nginx
  tolerations:
  - key: band
    operator: Equal
    value: beatles
    effect: NoSchedule
